[Theme]
Current=breeze

[General]
Numlock=on
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
MaximumUid=60513
MinimumUid=1000
HideUsers=
HideShells=/sbin/nologin,/bin/false
